"""Structured Vector Motion v0.1 reference core."""

from .artifacts import (
    ArtifactBlob,
    ArtifactDescriptor,
    ArtifactError,
    ArtifactKind,
    ArtifactRepository,
    ArtifactResolver,
    ArtifactSnapshot,
    ArtifactStore,
    ArtifactWriter,
)
from .backends import GeometryBackend, GeometryBackendError
from .evaluator import EvaluationState, Evaluator, Quality
from .operations import (
    OperationDefinition,
    OperationExecutionContext,
    OperationRegistry,
    OperationValidationError,
    ValueType,
    get_operation_registry,
)
from .proposals import (
    AdapterRequest,
    EntityDiffPreview,
    EvaluationReport,
    GeneratorProvenance,
    MatchScorePreview,
    PreviewArtifact,
    Proposal,
    ProposalAcceptor,
    ProposalArtifactError,
    ProposalConflictError,
    ProposalPolicyError,
    ProposalPreview,
    ProposalProvider,
    StructuralCandidatePreview,
    StructuralRelationPreview,
)
from .revisions import (
    COMPONENT_PROMOTION_IDENTITY,
    STRUCTURAL_RELATIONS_IDENTITY,
    AppendReferencesChange,
    AppendSceneFragmentChange,
    PromoteComponentsChange,
    PromotedComponent,
    ReplaceSceneFragmentChange,
    RevisionStore,
    SetOperationParameterChange,
    SplitEntityChange,
    SplitPart,
    Transaction,
    promoted_component_entity_id,
)
from .scene import EvaluatedEntity, EvaluatedScene, EvaluatedStyle, build_evaluated_scene

__all__ = [
    "Evaluator",
    "ArtifactError",
    "ArtifactBlob",
    "ArtifactDescriptor",
    "ArtifactKind",
    "ArtifactResolver",
    "ArtifactRepository",
    "ArtifactSnapshot",
    "ArtifactStore",
    "ArtifactWriter",
    "GeometryBackend",
    "GeometryBackendError",
    "EvaluationState",
    "Quality",
    "OperationDefinition",
    "OperationExecutionContext",
    "OperationRegistry",
    "OperationValidationError",
    "ValueType",
    "get_operation_registry",
    "RevisionStore",
    "COMPONENT_PROMOTION_IDENTITY",
    "STRUCTURAL_RELATIONS_IDENTITY",
    "AppendSceneFragmentChange",
    "AppendReferencesChange",
    "PromoteComponentsChange",
    "PromotedComponent",
    "ReplaceSceneFragmentChange",
    "SetOperationParameterChange",
    "SplitEntityChange",
    "SplitPart",
    "Transaction",
    "promoted_component_entity_id",
    "EvaluatedEntity",
    "EvaluatedScene",
    "EvaluatedStyle",
    "build_evaluated_scene",
    "AdapterRequest",
    "EntityDiffPreview",
    "EvaluationReport",
    "GeneratorProvenance",
    "MatchScorePreview",
    "PreviewArtifact",
    "Proposal",
    "ProposalAcceptor",
    "ProposalArtifactError",
    "ProposalConflictError",
    "ProposalPolicyError",
    "ProposalProvider",
    "ProposalPreview",
    "StructuralCandidatePreview",
    "StructuralRelationPreview",
]
